# Generated by Django 3.0.2 on 2020-02-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=250)),
                ('question', models.CharField(max_length=750)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
