# Generated by Django 2.2.7 on 2020-02-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentevents',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(default='', upload_to='portal/files')),
                ('filename', models.CharField(max_length=400)),
            ],
        ),
    ]
