# Generated by Django 3.0.2 on 2020-02-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_currentevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('lno', models.AutoField(primary_key=True, serialize=False)),
                ('lname', models.CharField(max_length=50)),
                ('lcontent', models.CharField(max_length=250)),
            ],
        ),
    ]
