# Generated by Django 3.0.2 on 2020-02-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('nno', models.AutoField(primary_key=True, serialize=False)),
                ('nname', models.CharField(max_length=50)),
                ('news', models.CharField(max_length=250)),
            ],
        ),
    ]
