# Generated by Django 3.0.2 on 2020-02-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('applicantno', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pass1', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
