# Generated by Django 3.0.2 on 2020-02-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
