# Generated by Django 3.0.2 on 2020-03-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imaged',
            fields=[
                ('imageno', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
